// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6T92AhgTrfyQEXJhtmSK6G5vtUeapsUE',
    appId: '1:44253640797:android:2a01242abde3cf671635b4',
    messagingSenderId: '44253640797',
    projectId: 'institutionapp-1cc1e',
    databaseURL: 'https://institutionapp-1cc1e-default-rtdb.firebaseio.com',
    storageBucket: 'institutionapp-1cc1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKQv3FG36lmlu7KW-0wnZs6YqCMe-A8ms',
    appId: '1:44253640797:ios:e6a55286fe8ca8441635b4',
    messagingSenderId: '44253640797',
    projectId: 'institutionapp-1cc1e',
    databaseURL: 'https://institutionapp-1cc1e-default-rtdb.firebaseio.com',
    storageBucket: 'institutionapp-1cc1e.appspot.com',
    iosBundleId: 'com.example.userapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwFoIj7s_ZlNY-3K99IYEcxtP9Li44G48',
    appId: '1:44253640797:web:98e8f8c28b6c91991635b4',
    messagingSenderId: '44253640797',
    projectId: 'institutionapp-1cc1e',
    authDomain: 'institutionapp-1cc1e.firebaseapp.com',
    databaseURL: 'https://institutionapp-1cc1e-default-rtdb.firebaseio.com',
    storageBucket: 'institutionapp-1cc1e.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKQv3FG36lmlu7KW-0wnZs6YqCMe-A8ms',
    appId: '1:44253640797:ios:e6a55286fe8ca8441635b4',
    messagingSenderId: '44253640797',
    projectId: 'institutionapp-1cc1e',
    databaseURL: 'https://institutionapp-1cc1e-default-rtdb.firebaseio.com',
    storageBucket: 'institutionapp-1cc1e.appspot.com',
    iosBundleId: 'com.example.userapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwFoIj7s_ZlNY-3K99IYEcxtP9Li44G48',
    appId: '1:44253640797:web:81a8006434b1fefa1635b4',
    messagingSenderId: '44253640797',
    projectId: 'institutionapp-1cc1e',
    authDomain: 'institutionapp-1cc1e.firebaseapp.com',
    databaseURL: 'https://institutionapp-1cc1e-default-rtdb.firebaseio.com',
    storageBucket: 'institutionapp-1cc1e.appspot.com',
  );

}